project:
  type: book

book:
  title: "Workbench Developer's Guide"
  description: |
    Learn how to build, debug, and contribute to the components that make up
    The Carpentries Workbench.
  author: "Zhian N. Kamvar"
  date: '2023-12-31'
  cover-image: 'images/cover.jpg'
  reader-mode: true
  repo-url: https://github.com/carpentries/workbench-dev/
  site-url: https://carpentries.github.io/workbench-dev/
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - testing.qmd
    - part: "Design Considerations"
      chapters:
      - flow.qmd
      - features.qmd
    - part: "{sandpaper} User Interface"
      chapters:
      - sandpaper/intro.qmd
      - sandpaper/testing.qmd
      - sandpaper/package-cache.qmd
    - part: "{pegboard} Validation and Parsing"
      chapters:
      - pegboard/intro.qmd
    - part: "{varnish} Web Styling"
      chapters:
      - varnish/intro.qmd
      # - varnish/testing.qmd
      # - varnish/rendering.qmd
    - part: "Package Distribution"
      chapters:
      - releases.qmd
      - hotfixes.qmd
    - part: "Remote Deployment and Management"
      chapters:
      - remote/intro.qmd
      - remote/deploy.qmd
      - remote/pull-request.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - sop.qmd
    - flight-rules.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: guide.scss
  # pdf:
  #   documentclass: scrreprt



